language: julia
os:
    - osx
    - linux
julia:
    - 0.6
    - nightly
notifications:
  email: false

script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("TSne", coverage=true)'

after_success:
    - julia -e 'cd(Pkg.dir("TSne")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
